{"name": "Class ArithmeticException", "module": "java.base", "package": "java.lang", "text": "Thrown when an exceptional arithmetic condition has occurred. For\n example, an integer \"divide by zero\" throws an\n instance of this class.\n\n ArithmeticException objects may be constructed by the\n virtual machine as if suppression were disabled and/or the\n stack trace was not writable.", "codes": ["public class ArithmeticException\nextends RuntimeException"], "fields": [], "methods": []}