{"name": "Class AttributeInUseException", "module": "java.naming", "package": "javax.naming.directory", "text": "This exception is thrown when an operation attempts\n to add an attribute that already exists.\n \n Synchronization and serialization issues that apply to NamingException\n apply directly here.", "codes": ["public class AttributeInUseException\nextends NamingException"], "fields": [], "methods": []}