{"name": "Class AuthenticationException", "module": "java.naming", "package": "javax.naming", "text": "This exception is thrown when an authentication error occurs while\n accessing the naming or directory service.\n An authentication error can happen, for example, when the credentials\n supplied by the user program are invalid or otherwise fail to\n authenticate the user to the naming/directory service.\n\n If the program wants to handle this exception in particular, it\n should catch AuthenticationException explicitly before attempting to\n catch NamingException. After catching AuthenticationException, the\n program could reattempt the authentication by updating\n the resolved context's environment properties with the appropriate\n credentials.\n \n Synchronization and serialization issues that apply to NamingException\n apply directly here.", "codes": ["public class AuthenticationException\nextends NamingSecurityException"], "fields": [], "methods": []}