{"name": "Class DirectoryIteratorException", "module": "java.base", "package": "java.nio.file", "text": "Runtime exception thrown if an I/O error is encountered when iterating over\n the entries in a directory. The I/O error is retrieved as an IOException using the getCause() method.", "codes": ["public final class DirectoryIteratorException\nextends ConcurrentModificationException"], "fields": [], "methods": [{"method_name": "getCause", "method_sig": "public IOException getCause()", "description": "Returns the cause of this exception."}]}