{"name": "Class TransportTimeoutException", "module": "jdk.jdi", "package": "com.sun.jdi.connect", "text": "This exception may be thrown as a result of a timeout\n when attaching to a target VM, or waiting to accept a\n connection from a target VM.\n\n  When attaching to a target VM, using attach this\n exception may be thrown if the connector supports a timeout\n connector argument. Similiarly,\n when waiting to accept a connection from a target VM,\n using accept this\n exception may be thrown if the connector supports a\n timeout connector argument when accepting.\n\n  In addition, for developers creating TransportService implementations this exception is thrown when\n attach times out when establishing a\n connection to a target VM, or accept\n times out while waiting for a target VM to connect. ", "codes": ["public class TransportTimeoutException\nextends IOException"], "fields": [], "methods": []}